(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const r of t.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&i(r)}).observe(document,{childList:!0,subtree:!0});function c(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=c(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",()=>{const s=document.querySelector(".mobile-menu-btn"),a=document.querySelector(".mobile-menu"),c=document.querySelector(".mobile-menu-icon use"),i=document.body;function e(){const o=a.classList.contains("is-open"),n=c.getAttribute("href").split("#")[0];a.classList.toggle("is-open"),s.setAttribute("aria-expanded",!o),c.setAttribute("href",o?n+"#icon-menu":n+"#icon-close"),i.style.overflow=o?"":"hidden"}s&&a&&(s.addEventListener("click",n=>{n.stopPropagation(),e()}),document.querySelectorAll(".mobile-nav-link").forEach(n=>{n.addEventListener("click",()=>{e()})}),document.addEventListener("click",n=>{a.classList.contains("is-open")&&!n.target.closest(".mobile-menu")&&!n.target.closest(".mobile-menu-btn")&&e()}),a.addEventListener("click",n=>{n.stopPropagation()}),document.addEventListener("keydown",n=>{n.key==="Escape"&&a.classList.contains("is-open")&&e()}));const t=window.location.pathname;document.querySelectorAll(".nav-link, .mobile-nav-link").forEach(o=>{o.classList.remove("active")}),t.includes("catalog.html")?document.querySelectorAll('[data-page="catalog"]').forEach(o=>{o.classList.add("active")}):t.includes("mylibrary.html")?document.querySelectorAll('[data-page="library"]').forEach(o=>{o.classList.add("active")}):document.querySelectorAll('[data-page="home"]').forEach(o=>{o.classList.add("active")})});const h="0ce25b1b3df50695af6eae55a386f147",p="https://api.themoviedb.org/3",v="https://image.tmdb.org/t/p/original";async function g(){return(await(await fetch(`${p}/trending/movie/day?api_key=${h}`)).json()).results}async function b(){var c;const s=document.getElementById("hero-section");try{let t=function(r){const o=r/2,n=Math.floor(o),u=o%1>=.25&&o%1<=.75,f=5-n-(u?1:0);let d="";for(let l=0;l<n;l++)d+='<span class="star full">★</span>';u&&(d+='<span class="star half">★</span>');for(let l=0;l<f;l++)d+='<span class="star empty">☆</span>';return d};var a=t;const i=await g();if(!i||i.length===0){m(s);return}const e=i[Math.floor(Math.random()*i.length)];s.style.backgroundImage=`url('${v}${e.backdrop_path}')`,s.innerHTML=`
      <div class="hero-content">
        <h1 class="hero-title">${e.title}</h1>
        <p class="hero-rating">${t(e.vote_average)}</p>
        <p class="hero-overview">${((c=e.overview)==null?void 0:c.slice(0,200))||"No description available."}</p>
        <div class="hero-buttons">
          <button class="hero-button" data-id="${e.id}" id="more-details-btn">More details</button>
          <button class="hero-button" data-id="${e.id}" id="watch-trailer-btn">Watch trailer</button>
        </div>
      </div>
    `,document.getElementById("more-details-btn").addEventListener("click",()=>{const r=new CustomEvent("openDetailsModal",{detail:{id:e.id}});window.dispatchEvent(r)}),document.getElementById("watch-trailer-btn").addEventListener("click",()=>{const r=new CustomEvent("openTrailerModal",{detail:{id:e.id}});window.dispatchEvent(r)})}catch(i){console.error("Hata oluştu:",i),m(s)}}function m(s){s.style.backgroundImage="url('../img/heroDefault.png')",s.innerHTML=`
    <div class="hero-content">
      <h1 class="hero-title">Welcome to Cinemania</h1>
      <p class="hero-overview">Discover the hottest movies trending today.</p>
      <div class="hero-buttons">
        <a href="/catalog.html" class="hero-button">Get Started</a>
      </div>
    </div>
  `}b();
//# sourceMappingURL=index.js.map
